include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - always_declare_return_types
    - type_annotate_public_apis
    - avoid_types_on_closure_parameters

    - avoid_empty_else
    - avoid_unnecessary_containers
    - no_logic_in_create_state

    - use_key_in_widget_constructors
    - prefer_final_locals
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new
    - avoid_unused_constructor_parameters

    - unnecessary_null_checks
    - use_if_null_to_convert_nulls_to_bools

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    invalid_annotation_target: error
